### ISSUE TITLE
Any idea how to handle the didSelect Delegate function?

### ISSUE THREAD

**Issue by patchthecode** [AveryVine/PersonalWebsite#59]
Any idea how to handle the `didSelect` Delegate function?

Lets say we have a CollectionView inside of a stack View.
```swift
Vstack {
   Text("Tapped Text")
   CollectionView()
```

Now I want when you tap on a collectionView cell, it should let its parent know that the cell was tapped. The Parent should replace the text in `Tapped Text` with the data tapped in the cell. How do we do this?

Basically i need to know how to handle the didSelect delegate function and report back to parentView

**Comment by AveryVine** [comment]
Hey. This question isn’t relevant to this project, so I’m gonna go ahead and close it. I’d suggest you look up some SwiftUI tutorials online. Good luck!
